// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    public class SteamVR_Input_ActionSet_default_In : SteamVR_Action_List
    {
        public SteamVR_Action_Boolean GrabGrip;

        public SteamVR_Action_Boolean GrabPinch;

        public SteamVR_Action_Boolean InteractUI;

        public SteamVR_Action_Pose Pose;

        public SteamVR_Action_Skeleton SkeletonLeftHand;

        public SteamVR_Action_Skeleton SkeletonRightHand;

        public SteamVR_Action_Single Squeeze;

        public SteamVR_Action_Boolean Teleport;
    }
}